In [ ]:
http://github.com/mariamhamza3019-star/Helicobacter-pylori-/blob/main/embedding_generator.py

In [ ]:
!git clone https://github.com/mariamhamza3019-star/Helicobacter-pylori-.git

Cloning into 'Helicobacter-pylori-'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 33 (delta 1), reused 20 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (33/33), 1.94 MiB | 8.84 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [ ]:
!pip install -q faiss-cpu sentence-transformers pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 13.4 MB/s eta 0:00:00

In [ ]:
import json
import os
import numpy as np
import pandas as pd
import faiss
from sentence_transformers import SentenceTransformer

ACG_FILE = "chunks_with_embeddings.json"
# Output files
INDEX_FILE = "h_pylori_faiss.index"
METADATA_FILE = "h_pylori_metadata.json"
RESULTS_FILE = "retrieval_results.csv"
#model
MODEL_NAME = "pritamdeka/S-BioBert-snli-multinli-stsb"

#loading embeddings

In [ ]:
def load_embedding_file(file_path):
    print(f"\n Loading: {file_path}")

    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, dict) and "chunks" in data:
        chunks = data["chunks"]
        file_metadata = data.get("metadata", {})
    else:
        chunks = data
        file_metadata = {}

    print(f"Number of chunks: {len(chunks)}")

    if file_metadata:
        print(f"Embedding model: {file_metadata.get('embedding_model', 'N/A')}")
        print(f"Embedding dimension: {file_metadata.get('embedding_dimension', 'N/A')}")

    return chunks, file_metadata


chunks, embedding_metadata = load_embedding_file(ACG_FILE)

 Loading: chunks_with_embeddings.json
Number of chunks: 103
Embedding model: pritamdeka/S-BioBert-snli-multinli-stsb
Embedding dimension: 768

#validate

In [ ]:
missing_embeddings = [
    chunk["chunk_id"]
    for chunk in chunks
    if "embedding" not in chunk
]

if missing_embeddings:
    print(f" {len(missing_embeddings)} chunks are missing embeddings")
    print("Examples:", missing_embeddings[:10])
else:
    print(" All chunks have embeddings")


chunk_ids = [chunk["chunk_id"] for chunk in chunks]

if len(chunk_ids) == len(set(chunk_ids)):
    print("All chunk IDs are unique")
else:
    print(" Duplicate chunk IDs found")

 All chunks have embeddings
All chunk IDs are unique

#embedding matrix

In [ ]:
embeddings = np.array(
    [chunk["embedding"] for chunk in chunks],
    dtype="float32"
)

print("Embedding matrix shape:", embeddings.shape)
print("Number of chunks:", embeddings.shape[0])
print("Vector dimension:", embeddings.shape[1])

Embedding matrix shape: (103, 768)
Number of chunks: 103
Vector dimension: 768

#faiss index

In [ ]:
dimension = embeddings.shape[1]

# Normalize for cosine similarity
faiss.normalize_L2(embeddings)

# Inner Product on normalized vectors = cosine similarity
index = faiss.IndexFlatIP(dimension)

index.add(embeddings)


print(f"Vector dimension : {dimension}")
print(f"Indexed chunks   : {index.ntotal}")
print("Similarity       : Cosine similarity")

Vector dimension : 768
Indexed chunks   : 103
Similarity       : Cosine similarity

In [ ]:
faiss.write_index(index, INDEX_FILE)

INDEX_FILE

'h_pylori_faiss.index'

#save metadata

In [ ]:
metadata = []

for chunk in chunks:
    metadata.append({
        "chunk_id": chunk.get("chunk_id", ""),
        "document_id": chunk.get("document_id", ""),
        "text": chunk.get("text", ""),
        "page": chunk.get("page", chunk.get("page_start", "")),
        "section": chunk.get("section", ""),
        "subsection": chunk.get("subsection", ""),
        "source": chunk.get("source", ""),
        "topic": chunk.get("topic", ""),
        "citation": chunk.get("citation", ""),
        "content_type": chunk.get("content_type", "")
    })


with open(METADATA_FILE, "w", encoding="utf-8") as f:
    json.dump(metadata, f, ensure_ascii=False, indent=2)

METADATA_FILE

'h_pylori_metadata.json'

In [28]:
print(f"Loading embedding model: {MODEL_NAME}")

model = SentenceTransformer(MODEL_NAME)

print("Model loaded")

Loading embedding model: pritamdeka/S-BioBert-snli-multinli-stsb

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Model loaded

#Retrieval function

In [29]:
def retrieve(query, top_k=5):

    # Embed the user's query
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    ).astype("float32")

    # Normalize query
    faiss.normalize_L2(query_embedding)

    # Search
    scores, indices = index.search(
        query_embedding,
        top_k
    )

    results = []

    for score, idx in zip(scores[0], indices[0]):

        if idx == -1:
            continue

        chunk = chunks[idx]

        results.append({
            "chunk_id": chunk.get("chunk_id", ""),
            "score": round(float(score), 4),
            "text": chunk.get("text", ""),
            "document_id": chunk.get("document_id", ""),
            "page": chunk.get("page", chunk.get("page_start", "")),
            "section": chunk.get("section", ""),
            "subsection": chunk.get("subsection", ""),
            "source": chunk.get("source", ""),
            "topic": chunk.get("topic", ""),
            "citation": chunk.get("citation", "")
        })

    return results

#test

In [30]:
query = "What is the recommended treatment for H. pylori infection?"

results = retrieve(query, top_k=5)

for i, result in enumerate(results, start=1):

    print(f"RANK {i}")


    print(f"Chunk ID : {result['chunk_id']}")
    print(f"Score    : {result['score']}")
    print(f"Source   : {result['source']}")
    print(f"Page     : {result['page']}")
    print(f"Section  : {result['section']}")

    print("\nText:")
    print(result["text"])

RANK 1
Chunk ID : ACG_0072
Score    : 0.7101
Source   : ACG Clinical Guideline 2024: Treatment of Helicobacter pylori Infection
Page     : 17
Section  : ERADICATING HELICOBACTER PYLORI INFECTION IN TREATMENT-EXPERIENCED PATIENTS

Text:
5. In treatment-experienced patients with persistent H. pylori infection that is confirmed to be clarithromycin-sensitive, PPI- or PCAB-clarithromycin triple therapy is suggested. As the recommendations of this guideline for the first-line treatment of H. pylori infection are incorporated into clinical practice, a larger proportion of treatment-experienced patients with persistent H. pylori infection will have previously been treated with BQT, rifabutin triple therapy, or vonoprazanamoxicillin dual therapy. If, related to previous use, high cost, or a lack of availability, treatment regimens containing clarithromycin or levofloxacin need to be considered, antibiotic susceptibility testing (see Key concept 6) should be performed. Here, we discuss clarithromycin triple therapy as salvage therapy, whereas quinolone-based salvage therapy is discussed below. There are no RCTs or robust observational data from North America that evaluate clarithromycin triple therapy as salvage therapy after BQT, rifabutin triple therapy, or vonoprazanamoxicillin dual therapy. Thus, the guideline panel used expert consensus to suggest PPI- or PCAB-clarithromycin triple salvage therapy in patients with persistent H. pylori infection confirmed to be sensitive to clarithromycin by antibiotic susceptibility testing. As noted above, the bactericidal activity of clarithromycin and amoxicillin on susceptible H. pylori strains is critically dependent on achieving and maintaining adequate gastric acid suppression (intragastric pH .6).
RANK 2
Chunk ID : ACG_0005
Score    : 0.7006
Source   : ACG Clinical Guideline 2024: Treatment of Helicobacter pylori Infection
Page     : 2
Section  : INTRODUCTION

Text:
In some instances, key concepts are based on extrapolation of evidence and/or expert consensus. This guideline used GRADE methodology to evaluate treatment options for patients with H. pylori infection. We summarize treatment recommendations for patients with active H. pylori infection, as confirmed by a nonserological test, who have not been previously treated (i.e., "treatment-naive" patients) and those with persistent infection despite previous attempt(s) at eradication (i.e., "treatment-experienced" patients). Readers will notice substantial changes from the recommendations offered in the 2017 ACG CPG (6). These changes were largely motivated by important new data from North America including: 1. Rising rates of resistance to key antibiotics used to treat H. pylori, including clarithromycin and levofloxacin. This has led to reduced effectiveness of commonly used treatment regimens that contain these antibiotics. 2. Studies that have been conducted with novel treatment regimens featuring new antibiotic options (i.e., rifabutin) or more potent, next-generation gastric acid-suppressing agents (i.e., potassium-competitive acid blockers; PCABs) in treatment-naive individuals. As in previous versions, recommendations were based on the current, best available evidence with prioritization of evidence from studies conducted in North America. When unavailable, recommendations were based on studies conducted in other parts of the world and expert consensus.
RANK 3
Chunk ID : ACG_0001
Score    : 0.6966
Source   : ACG Clinical Guideline 2024: Treatment of Helicobacter pylori Infection
Page     : 1
Section  : ABSTRACT

Text:
Helicobacter pylori is a prevalent, global infectious disease that causes dyspepsia, peptic ulcer disease, and gastric cancer. The American College of Gastroenterology commissioned this clinical practice guideline (CPG) to inform the evidence-based management of patients with H. pylori infection in North America. This CPG used Grading of Recommendations, Assessment, Development, and Evaluation (GRADE) methodology to systematically analyze 11 Population, Intervention, Comparison, and Outcome questions and generate recommendations. Where evidence was insufficient or the topic did not lend itself to GRADE, expert consensus was used to create 6 key concepts. For treatment-naive patients with H. pylori infection, bismuth quadruple therapy (BQT) for 14 days is the preferred regimen when antibiotic susceptibility is unknown. Rifabutin triple therapy or potassium-competitive acid blocker dual therapy for 14 days is a suitable empiric alternative in patients without penicillin allergy. In treatment-experienced patients with persistent H. pylori infection, "optimized" BQT for 14 days is preferred for those who have not been treated with optimized BQT previously and for whom antibiotic susceptibility is unknown. In patients previously treated with optimized BQT, rifabutin triple therapy for 14 days is a suitable empiric alternative.
RANK 4
Chunk ID : ACG_0055
Score    : 0.6889
Source   : ACG Clinical Guideline 2024: Treatment of Helicobacter pylori Infection
Page     : 13
Section  : POST-TREATMENT TESTING FOR CURE

Text:
Results will inform clinicians either to consider an alternative treatment for H. pylori in those with persistent infection or a different dyspepsia treatment strategy in those with successful eradication. A negative post-treatment test result should be reassuring to patients and providers alike as a meta-analysis reported recurrence rates of 1% (95% CI 0.3%-3%) per year for persons in the United States who are successfully eradicated of their H. pylori infection. Thus, with the exception of Alaskan natives who have an H. pylori recurrence rate of more than 8%, recurrence of H. pylori infection after an evidence-based treatment regimen is quite rare in the United States (105). An added benefit of routinely testing for cure is the ability of providers to monitor their local treatment results and to change their approach if results with certain regimens are suboptimal (e.g., if under 85%). Low eradication rates in first-line therapy should prompt consideration of testing for resistance and/or adopting a different empiric regimen. It is encouraging that the recommendation for routine post-treatment test of cure in the 2017 ACG guideline has been accompanied by improved rates of post-treatment testing in clinical practice in the United States, from under 25% in 2005 to 60%-80%by 2019 (57,60,106). Nevertheless, these improvements should not discourage healthcare providers from further attempts at improving adherence to the recommendation for universal post-treatment testing.
RANK 5
Chunk ID : ACG_0019
Score    : 0.6867
Source   : ACG Clinical Guideline 2024: Treatment of Helicobacter pylori Infection
Page     : 5
Section  : INDICATIONS FOR HELICOBACTER PYLORI TESTING AND TREATMENT

Text:
In patients with functional dyspepsia, eradication of H. pylori infection only provides modest benefit. A recent meta-analysis identified 29 RCTs including 6,781 H. pylori-positive patients with functional dyspepsia (26). They reported that treatment of H. pylori was superior to control (PPI, prokinetics, or placebo) for symptom cure (RR of symptoms not being cured 5 0.91; 95% CI 0.88-0.94, number needed to treat [NNT] 5 14; 95% CI 11-21) and symptom improvement (RR 0.84; 95% CI 0.78-0.91, NNT 5 9; 95% CI 7-17). The impact on symptoms was larger in patients with successful cure of H. pylori than in those who were not successfully cured of their infection (RR 0.65; 95% CI 0.52-0.82, NNT 5 4.5, 95% CI 3-9). Overall adverse events (RR 2.19; 95% CI 1.10-4.37) and adverse events leading to withdrawal (RR 2.60; 95% CI 1.47-4.58) were reported more commonly with antibiotic therapy for H. pylori. Although clinical benefits of H. pylori treatment are modest, it bears emphasizing that eradication of H. pylori is one of the only potentially curative treatments for patients with functional dyspepsia (25), and reduces the risk of other downstream complications of chronic H. pylori infection. In both uninvestigated and functional dyspepsia, benefits range from symptomrelief to decreased healthcare utilization.

In [31]:
test_queries = [
    "What is the recommended treatment for H. pylori infection?",
    "When should eradication of H. pylori be confirmed?",
    "What are the indications for testing for H. pylori?",
    "What is the recommended duration of H. pylori treatment?",
    "What should be done after H. pylori treatment fails?",
    "What are the recommended first-line therapies for H. pylori?",
    "When should patients be tested for H. pylori after treatment?"
]


all_results = []

for query in test_queries:

    results = retrieve(query, top_k=5)

    for rank, result in enumerate(results, start=1):

        all_results.append({
            "query": query,
            "rank": rank,
            "chunk_id": result["chunk_id"],
            "score": result["score"],
            "source": result["source"],
            "document_id": result["document_id"],
            "page": result["page"],
            "section": result["section"],
            "text": result["text"]
        })


results_df = pd.DataFrame(all_results)

results_df

,query,rank,chunk_id,score,source,document_id,page,section,text
0,What is the recommended treatment for H. pylor...,1,ACG_0072,0.7101,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...
1,What is the recommended treatment for H. pylor...,2,ACG_0005,0.7006,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"In some instances, key concepts are based on e..."
2,What is the recommended treatment for H. pylor...,3,ACG_0001,0.6966,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,1,ABSTRACT,"Helicobacter pylori is a prevalent, global inf..."
3,What is the recommended treatment for H. pylor...,4,ACG_0055,0.6889,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...
4,What is the recommended treatment for H. pylor...,5,ACG_0019,0.6867,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,"In patients with functional dyspepsia, eradica..."
5,When should eradication of H. pylori be confir...,1,ACG_0029,0.6713,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,6,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,After successful eradication of H. pylori infe...
6,When should eradication of H. pylori be confir...,2,ACG_0053,0.6610,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,4. All patients who are treated for H. pylori ...
7,When should eradication of H. pylori be confir...,3,ACG_0055,0.6522,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...
8,When should eradication of H. pylori be confir...,4,ACG_0005,0.6003,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"In some instances, key concepts are based on e..."
9,When should eradication of H. pylori be confir...,5,ACG_0017,0.5994,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,2. The determination of when to test for—and t...
10,What are the indications for testing for H. py...,1,ACG_0021,0.7205,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,Table 4. Indications for H. pylori testing and...
11,What are the indications for testing for H. py...,2,ACG_0054,0.6438,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Similar to urea breath testing and fecal antig...
12,What are the indications for testing for H. py...,3,ACG_0084,0.6429,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,19,ANTIBIOTIC SUSCEPTIBILITY TESTING,6. H. pylori antibiotic susceptibility tests u...
13,What are the indications for testing for H. py...,4,ACG_0017,0.6299,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,2. The determination of when to test for—and t...
14,What are the indications for testing for H. py...,5,ACG_0004,0.6284,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"We also discuss the critically important, but ..."
15,What is the recommended duration of H. pylori ...,1,ACG_0072,0.6923,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...
16,What is the recommended duration of H. pylori ...,2,ACG_0011,0.6617,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,3,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,Recommendations for treatment-experienced pati...
17,What is the recommended duration of H. pylori ...,3,ACG_0074,0.6514,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,18,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,9. In treatment-experienced patients with pers...
18,What is the recommended duration of H. pylori ...,4,ACG_0005,0.6378,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"In some instances, key concepts are based on e..."
19,What is the recommended duration of H. pylori ...,5,ACG_0055,0.6361,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...
20,What should be done after H. pylori treatment ...,1,ACG_0055,0.6944,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...
21,What should be done after H. pylori treatment ...,2,ACG_0011,0.6204,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,3,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,Recommendations for treatment-experienced pati...
22,What should be done after H. pylori treatment ...,3,ACG_0056,0.6062,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,Treatment of patients with persistent H. pylor...
23,What should be done after H. pylori treatment ...,4,ACG_0072,0.6004,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...
24,What should be done after H. pylori treatment ...,5,ACG_0074,0.6001,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,18,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,9. In treatment-experienced patients with pers...
25,What are the recommended first-line therapies ...,1,ACG_0036,0.7055,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,9,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,2. In treatment-naive patients with H. pylori ...
26,What are the recommended first-line therapies ...,2,ACG_0072,0.7024,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...
27,What are the recommended first-line therapies ...,3,ACG_0010,0.6862,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,3,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,Table 2. Guideline recommendations Recommendat...
28,What are the recommended first-line therapies ...,4,ACG_0001,0.6812,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,1,ABSTRACT,"Helicobacter pylori is a prevalent, global inf..."
29,What are the recommended first-line therapies ...,5,ACG_0005,0.6669,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"In some instances, key concepts are based on e..."
30,When should patients be tested for H. pylori a...,1,ACG_0055,0.7538,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...
31,When should patients be tested for H. pylori a...,2,ACG_0021,0.6707,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,Table 4. Indications for H. pylori testing and...
32,When should patients be tested for H. pylori a...,3,ACG_0053,0.6519,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,4. All patients who are treated for H. pylori ...
33,When should patients be tested for H. pylori a...,4,ACG_0072,0.6463,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...
34,When should patients be tested for H. pylori a...,5,ACG_0017,0.6310,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,2. The determination of when to test for—and t...

In [39]:
# Manual mapping: each of your test_queries -> closest gold question's expect_sections
# (matched by hand from gold_questions.json)
query_expected_sections = {
    "What is the recommended treatment for H. pylori infection?":
        ["ERADICATING HELICOBACTER PYLORI INFECTION IN TREATMENT-NAIVE PATIENTS", "ABSTRACT"],  # ~Q01

    "When should eradication of H. pylori be confirmed?":
        ["POST-TREATMENT TESTING FOR CURE"],  # ~Q12

    "What are the indications for testing for H. pylori?":
        ["INDICATIONS FOR HELICOBACTER PYLORI TESTING AND TREATMENT", "ABSTRACT"],  # ~Q14

    "What is the recommended duration of H. pylori treatment?":
        ["ERADICATING HELICOBACTER PYLORI INFECTION IN TREATMENT-NAIVE PATIENTS", "ABSTRACT"],  # ~Q02

    "What should be done after H. pylori treatment fails?":
        ["ERADICATING HELICOBACTER PYLORI INFECTION IN TREATMENT-EXPERIENCED PATIENTS"],  # ~Q10

    "What are the recommended first-line therapies for H. pylori?":
        ["ERADICATING HELICOBACTER PYLORI INFECTION IN TREATMENT-NAIVE PATIENTS", "ABSTRACT"],  # ~Q01

    "When should patients be tested for H. pylori after treatment?":
        ["POST-TREATMENT TESTING FOR CURE"],  # ~Q12/Q13
}

all_results = []

for query in test_queries:
    results = retrieve(query, top_k=5)
    expected = set(query_expected_sections.get(query, []))
    retrieved_sections = {r["section"] for r in results}
    query_passed = bool(retrieved_sections & expected)  # any overlap = pass

    for rank, result in enumerate(results, start=1):
        chunk_relevant = result["section"] in expected  # per-chunk auto-label

        all_results.append({
            "query": query,
            "rank": rank,
            "chunk_id": result["chunk_id"],
            "score": result["score"],
            "source": result["source"],
            "document_id": result["document_id"],
            "page": result["page"],
            "section": result["section"],
            "text": result["text"],
            "relevant": chunk_relevant,          # <-- auto-filled, no manual reading
            "query_passed": query_passed
        })

results_df = pd.DataFrame(all_results)

# Overall recall@5 across your 7 queries
recall_at_5 = results_df.groupby("query")["query_passed"].first().mean()
print(f"Recall@5: {recall_at_5:.2%}")

results_df

Recall@5: 85.71%

,query,rank,chunk_id,score,source,document_id,page,section,text,relevant,query_passed
0,What is the recommended treatment for H. pylor...,1,ACG_0072,0.7101,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...,False,True
1,What is the recommended treatment for H. pylor...,2,ACG_0005,0.7006,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"In some instances, key concepts are based on e...",False,True
2,What is the recommended treatment for H. pylor...,3,ACG_0001,0.6966,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,1,ABSTRACT,"Helicobacter pylori is a prevalent, global inf...",True,True
3,What is the recommended treatment for H. pylor...,4,ACG_0055,0.6889,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...,False,True
4,What is the recommended treatment for H. pylor...,5,ACG_0019,0.6867,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,"In patients with functional dyspepsia, eradica...",False,True
5,When should eradication of H. pylori be confir...,1,ACG_0029,0.6713,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,6,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,After successful eradication of H. pylori infe...,False,True
6,When should eradication of H. pylori be confir...,2,ACG_0053,0.6610,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,4. All patients who are treated for H. pylori ...,True,True
7,When should eradication of H. pylori be confir...,3,ACG_0055,0.6522,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...,True,True
8,When should eradication of H. pylori be confir...,4,ACG_0005,0.6003,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"In some instances, key concepts are based on e...",False,True
9,When should eradication of H. pylori be confir...,5,ACG_0017,0.5994,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,2. The determination of when to test for—and t...,False,True
10,What are the indications for testing for H. py...,1,ACG_0021,0.7205,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,Table 4. Indications for H. pylori testing and...,True,True
11,What are the indications for testing for H. py...,2,ACG_0054,0.6438,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Similar to urea breath testing and fecal antig...,False,True
12,What are the indications for testing for H. py...,3,ACG_0084,0.6429,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,19,ANTIBIOTIC SUSCEPTIBILITY TESTING,6. H. pylori antibiotic susceptibility tests u...,False,True
13,What are the indications for testing for H. py...,4,ACG_0017,0.6299,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,2. The determination of when to test for—and t...,True,True
14,What are the indications for testing for H. py...,5,ACG_0004,0.6284,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"We also discuss the critically important, but ...",False,True
15,What is the recommended duration of H. pylori ...,1,ACG_0072,0.6923,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...,False,False
16,What is the recommended duration of H. pylori ...,2,ACG_0011,0.6617,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,3,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,Recommendations for treatment-experienced pati...,False,False
17,What is the recommended duration of H. pylori ...,3,ACG_0074,0.6514,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,18,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,9. In treatment-experienced patients with pers...,False,False
18,What is the recommended duration of H. pylori ...,4,ACG_0005,0.6378,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"In some instances, key concepts are based on e...",False,False
19,What is the recommended duration of H. pylori ...,5,ACG_0055,0.6361,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...,False,False
20,What should be done after H. pylori treatment ...,1,ACG_0055,0.6944,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...,False,True
21,What should be done after H. pylori treatment ...,2,ACG_0011,0.6204,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,3,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,Recommendations for treatment-experienced pati...,True,True
22,What should be done after H. pylori treatment ...,3,ACG_0056,0.6062,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,Treatment of patients with persistent H. pylor...,True,True
23,What should be done after H. pylori treatment ...,4,ACG_0072,0.6004,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...,True,True
24,What should be done after H. pylori treatment ...,5,ACG_0074,0.6001,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,18,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,9. In treatment-experienced patients with pers...,True,True
25,What are the recommended first-line therapies ...,1,ACG_0036,0.7055,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,9,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,2. In treatment-naive patients with H. pylori ...,True,True
26,What are the recommended first-line therapies ...,2,ACG_0072,0.7024,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...,False,True
27,What are the recommended first-line therapies ...,3,ACG_0010,0.6862,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,3,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,Table 2. Guideline recommendations Recommendat...,True,True
28,What are the recommended first-line therapies ...,4,ACG_0001,0.6812,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,1,ABSTRACT,"Helicobacter pylori is a prevalent, global inf...",True,True
29,What are the recommended first-line therapies ...,5,ACG_0005,0.6669,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,2,INTRODUCTION,"In some instances, key concepts are based on e...",False,True
30,When should patients be tested for H. pylori a...,1,ACG_0055,0.7538,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,Results will inform clinicians either to consi...,True,True
31,When should patients be tested for H. pylori a...,2,ACG_0021,0.6707,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,Table 4. Indications for H. pylori testing and...,False,True
32,When should patients be tested for H. pylori a...,3,ACG_0053,0.6519,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,13,POST-TREATMENT TESTING FOR CURE,4. All patients who are treated for H. pylori ...,True,True
33,When should patients be tested for H. pylori a...,4,ACG_0072,0.6463,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...,5. In treatment-experienced patients with pers...,False,True
34,When should patients be tested for H. pylori a...,5,ACG_0017,0.6310,ACG Clinical Guideline 2024: Treatment of Heli...,ACG_2024,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...,2. The determination of when to test for—and t...,False,True

#saving results

In [36]:
results_df.to_csv(
    RESULTS_FILE,
    index=False,
    encoding="utf-8-sig"
)

print(f"Retrieval results saved: {RESULTS_FILE}")

Retrieval results saved: retrieval_results.csv

#best result for every query

In [37]:
top_results = results_df[
    results_df["rank"] == 1
][
    [
        "query",
        "chunk_id",
        "score",
        "source",
        "page",
        "section"
    ]
]

top_results

,query,chunk_id,score,source,page,section
0,What is the recommended treatment for H. pylor...,ACG_0072,0.7101,ACG Clinical Guideline 2024: Treatment of Heli...,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...
5,When should eradication of H. pylori be confir...,ACG_0029,0.6713,ACG Clinical Guideline 2024: Treatment of Heli...,6,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...
10,What are the indications for testing for H. py...,ACG_0021,0.7205,ACG Clinical Guideline 2024: Treatment of Heli...,5,INDICATIONS FOR HELICOBACTER PYLORI TESTING AN...
15,What is the recommended duration of H. pylori ...,ACG_0072,0.6923,ACG Clinical Guideline 2024: Treatment of Heli...,17,ERADICATING HELICOBACTER PYLORI INFECTION IN T...
20,What should be done after H. pylori treatment ...,ACG_0055,0.6944,ACG Clinical Guideline 2024: Treatment of Heli...,13,POST-TREATMENT TESTING FOR CURE
25,What are the recommended first-line therapies ...,ACG_0036,0.7055,ACG Clinical Guideline 2024: Treatment of Heli...,9,ERADICATING HELICOBACTER PYLORI INFECTION IN T...
30,When should patients be tested for H. pylori a...,ACG_0055,0.7538,ACG Clinical Guideline 2024: Treatment of Heli...,13,POST-TREATMENT TESTING FOR CURE

In [38]:
from google.colab import files

files.download(INDEX_FILE)
files.download(METADATA_FILE)
files.download(RESULTS_FILE)